"""empty message

Revision ID: da6d945cbc2a
Revises: 17303fbe3cc3
Create Date: 2021-03-11 09:38:46.423611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6d945cbc2a'
down_revision = '17303fbe3cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Cidades', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'cidades', ['Cidades'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'Cidades')
    # ### end Alembic commands ###
